version: "3.9"
services:
  rabbitmq:
  # https://github.com/docker-library/rabbitmq/issues/61#issuecomment-793995406
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    environment:
      - HOSTNAME=rabbitmq
      - RABBITMQ_NODENAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "512M"
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    volumes:
      - "./rabbitmq/etc/:/etc/rabbitmq/"
      - "./rabbitmq/data/:/var/lib/rabbitmq"
      - "./rabbitmq/logs/:/var/log/rabbitmq"
      # change permission of all dir -R (/etc, data, logs) to 100:101 ie rabbitmq:rabbitmq in container
    networks:
      - rabbitmq_go_net

  mongo:
    image: mongo
    container_name: "mongodb"
    restart: always
    volumes:
      - "./mongo/datadir:/data/db"
      - "./mongo/config:/data/configdb"
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: "2048M"
        reservations:
          cpus: "1.25"
          memory: "2048M"
    command: --wiredTigerCacheSizeGB .5
 
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  rabbitmq_go_net:
    driver: bridge
