version: '3.8'

services:
  node1:
    image: cassandra:latest
    container_name: node1
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_LISTEN_ADDRESS=node1
      - CASSANDRA_BROADCAST_ADDRESS=node1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - '9042:9042'
    volumes:
      - './data/node1:/var/lib/cassandra/data'
    mem_limit: 2g

  node2:
    image: cassandra:latest
    container_name: node2
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_LISTEN_ADDRESS=node2
      - CASSANDRA_BROADCAST_ADDRESS=node2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - '9043:9042'
    volumes:
      - './data/node2:/var/lib/cassandra/data'
    mem_limit: 2g

  node3:
    image: cassandra:latest
    container_name: node3
    environment:
      - CASSANDRA_CLUSTER_NAME=docker-cluster
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_LISTEN_ADDRESS=node3
      - CASSANDRA_BROADCAST_ADDRESS=node3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - '9044:9042'
    volumes:
      - './data/node3:/var/lib/cassandra/data'
    mem_limit: 2g

  reaper:
    image: thelastpickle/cassandra-reaper:latest
    container_name: reaper
    environment:
      - CASSANDRA_REAPER_AUTO_SNOOP=true
      - CASSANDRA_REAPER_STORAGE_TYPE=cassandra
      - CASSANDRA_REAPER_CASS_CONTACT_POINTS=node1,node2,node3
      - CASSANDRA_REAPER_CASS_NATIVE_PORT=9042
    ports:
      - '8080:8080'
    depends_on:
      - node1
      - node2
      - node3
